version: 2

jobs:

  build:
    docker:
      - image: circleci/node:12-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v12-{{ arch }}-{{ checksum "package.json" }}
            - node-v12-{{ arch }}-
            - node-v12- # used if checksum fails

      - run: npm install

      - save_cache:
          key: node-v12-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ~/usr/local/lib/node_modules
            - node_modules/

      - run: npm test

      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: test-results/
