references:

  filters_only_renovate_nori: &filters_only_renovate_nori
    branches:
      only: /(^renovate-.*|^nori\/.*)/

  filters_ignore_renovate_nori: &filters_ignore_renovate_nori
    branches:
      ignore: /(^renovate-.*|^nori\/.*|^main)/

version: 2.1

orbs:
  node: circleci/node@4.6.0

jobs:

  build:
    docker:
      - image: cimg/node:18.16

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v12-{{ arch }}-{{ checksum "package.json" }}
            - node-v12-{{ arch }}-
            - node-v12- # used if checksum fails

      - run: npm install

      - save_cache:
          key: node-v12-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ~/usr/local/lib/node_modules
            - node_modules/

      - run: npm test

      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: test-results/

workflows:
  version: 2

  build:
    jobs:
      - build:
          filters:
            <<: *filters_ignore_renovate_nori

  renovate-nori-build:
    jobs:
      - waiting-for-approval:
          type: approval
          filters:
            <<: *filters_only_renovate_nori
      - build:
          requires:
            - waiting-for-approval
